disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional

included:
  - Sources
  - Tests
  - .

excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

identifier_name:
  min_length: 1
  max_length: 40

indentation: 2